### ISSUE TITLE
invoking "make -j8 -l8" failed

### ISSUE THREAD

**Issue by acoudgo** [unitreerobotics/unitree_guide#10]
在把unitree_guide，unitree_legged_msgs和unitree_ros_master一起放在catkin_ws/src中catkin_make后出现的报错，应该如何解决？rosdep check后无依赖缺失（all system dependencies have been satisfied）
在把unitree_move_base放在catkin_ws/src中单独catkin_make编译后也出现类似问题 但提示的是：running command:"make -j8 -l8"in"/catkin_ws/build"

**Comment by xiaoliangstd** [comment]
你好，可以截一张您报错的终端图片我这边分析下

**Comment by acoudgo** [comment]
![IMG_0830](https://user-images.githubusercontent.com/93958098/224967909-61ed89a5-6da8-4fd3-92bf-2ac80e246065.jpg)

**Comment by xiaoliangstd** [comment]
图片我这边打开失败了，可以用preview看下显示正不正常

**Comment by acoudgo** [comment]
![7e2e6fabcc376d0bce6376330b0c9f64](https://user-images.githubusercontent.com/93958098/225188043-aef19327-b1f1-4680-99a0-e55ec450ef41.png)

**Comment by acoudgo** [comment]
![e32a73cda011e4497dd04e2566631675](https://user-images.githubusercontent.com/93958098/225190601-380b66c3-d2d0-438c-8332-f9f20505c819.png)

**Comment by xiaoliangstd** [comment]
您这ubuntu 是用Mac os 跑的？

**Comment by acoudgo** [comment]
我是有mac笔电 但这个ubuntu就是正常的主机安装的啊....好迷.....

**Comment by xiaoliangstd** [comment]
终端信息为啥会有 “apple” "Mac ox x" 之类的信息呢

**Comment by acoudgo** [comment]
我又去检查了一下cmake的安装版本 重新安装了一遍 确定了是cmake version 3.26.0 实在是想不通还有哪个环节会跟mac有关了

**Comment by LJoson** [comment]
你不要用最大数量核数去catkin_make试试，由于cpu核心性能问题，ros编译过程中会出现这类问题

**Comment by acoudgo** [comment]
我在win系统下重下了github上的文件 依然是invoking"make -j8 -l8"failed 但是报错和之前不一样 如下
![d5d4f94755dfa876fc060d264d45f529](https://user-images.githubusercontent.com/93958098/225215473-52073bd3-bc8e-477c-9d2b-4742bcf7d0c7.png)
然后 我又按照catkin_make -j1的方法 试了一次 是不是就是减少核数的方法 但还是报错 如下
![a8ab857f907bc89324d054390025d985](https://user-images.githubusercontent.com/93958098/225216164-c6467508-8eec-4ad1-847b-18c6973da70a.png)
请问还有什么方法可以处理这种情况

**Comment by xiaoliangstd** [comment]
hello, look at the terminal, there is a hint "cannot find -llcm", that means you haven't installed the lcm. Please refer to this link https://github.com/lcm-proj/lcm to install. By the way, unitree_legged_real package should not be a part of dependencies，which is at the unitree_ros_to_real package.  这是在别的问题的回答，可以参考下，终端提示有为什么编译不通过

**Comment by acoudgo** [comment]
![24866757a341c0e9192c9e20c5bdfd31](https://user-images.githubusercontent.com/93958098/225267572-1471afbd-79cc-4e06-a2ca-d3bca3b9fe95.png)
在lcm安装过程进行到cmake ..这一步时 遇到了下面的问题 请问有遇到过类似的情况吗  暂时没找到
原链接：https://blog.csdn.net/weixin_45467056/article/details/123569027
![ff04d3897c7d697c32e788c3422b5023](https://user-images.githubusercontent.com/93958098/225267627-4d0f571b-fe50-4448-b663-6608bf35f97f.png)

**Comment by xiaoliangstd** [comment]
这个请直接参考官方文档，其他的文章的情况我这边没遇到过，安装LCM的过程应该还是很简单的，不至与出错 ,  https://lcm-proj.github.io/lcm/content/build-instructions.html。
