### ISSUE TITLE
关于unitreeLeg.h的调用问题

### ISSUE THREAD

**Issue by Takagi0215** [unitreerobotics/unitree_guide#11]
1. 今天看完了第五章，想动手调用一下unitreeLeg.h的相关函数。编译过程中出现如图问题，请问大佬是代码写法有问题吗？
![45e5ffe7a06ad959bc1d000fa92129e](https://user-images.githubusercontent.com/127809894/225252708-82e25f3d-8373-40fa-89cc-fbf901bf4ff7.png)

2. 想看一下unitreeLeg.h里面函数的具体实现方法，请问应该在哪个文件查看呢？（例如想看一下calcPEe2B是怎么实现的）

**Comment by xiaoliangstd** [comment]
问题1：
1.
你的参数输入有问题，参考unitreeRobot.cpp文件中 A1Robot类的构造函数里的写法
_Legs[0] = new A1Leg(0, Vec3<double>( 0.1805, -0.047, 0));
    _Legs[1] = new A1Leg(1, Vec3<double>( 0.1805,  0.047, 0));
    _Legs[2] = new A1Leg(2, Vec3<double>(-0.1805, -0.047, 0));
    _Legs[3] = new A1Leg(3, Vec3<double>(-0.1805,  0.047, 0));

![unitree_leg](https://user-images.githubusercontent.com/37007970/225268154-7027314d-44d6-4b97-91b3-bfcafc490256.png)



2.第二种情况，一般应该是你CMakeLists.txt文件没把原文件链接进去 
例如： add_executable(test1 src/test1.cpp ${SRC_LIST})

问题2： 
可以学习下 使用 vscode 的 搜索工具，即左边 的 第二个 放大镜形状的按钮， 把你想要查找的函数实现 的名字放进去 ，按回车键即可看到整个工程中在那里使用到该函数

![vscode搜索](https://user-images.githubusercontent.com/37007970/225266108-4dec92cb-fdfe-4ab7-8b8e-e08709b97292.png)

**Comment by xiaoliangstd** [comment]
参考
unitreeLeg.h

![unitree_leg h](https://user-images.githubusercontent.com/37007970/225269608-4f9115ec-fb18-45b8-82ef-21ab93f74f40.png)
