### ISSUE TITLE
关于unitreeRobot.cpp

### ISSUE THREAD

**Issue by Alleneeous** [unitreerobotics/unitree_guide#23]
书上对_mass和_Ib都进行了介绍，但是没有解释_pcb，请问_pcb是什么呢？
![image](https://user-images.githubusercontent.com/65111761/227463904-ffac72ef-9b92-42d3-b766-0ff6bc3de757.png)

**Comment by xiaoliangstd** [comment]
_pcb是躯干重心在body系下的位置（一个三维度的量），主要用于计算各个足端力在躯干重心处产生的扭矩。

**Comment by xiaoliangstd** [comment]
但由于规划出的足端力等都是世界坐标系即{s}系下，所以在计算时要左乘个 from body to world 的 旋转矩阵，将相关的量转化到世界坐标系下，请参考85页 图6.3 中的pg
