### ISSUE TITLE
关于State_SwingTest.cpp

### ISSUE THREAD

**Issue by Alleneeous** [unitreerobotics/unitree_guide#25]
请问能否给出一段示例代码，以在此文件下，让右前腿运动一段摆线轨迹呢？

**Comment by xiaoliangstd** [comment]
你好，这个工程是配套书籍使用的，而且工程代码是全部开源的。您所说的让右前腿运动一段摆线轨迹，这个功能在现有代码里改改就可以实现，建议您在熟悉课程内容后自己尝试一下。
