### ISSUE TITLE
unitree_pointCloud_publisher

### ISSUE THREAD

**Issue by acoudgo** [unitreerobotics/unitree_guide#26]
请问在书上151页提到的unitree_pointCloud_publisher已经发布了吗 好像没有找到

**Comment by xiaoliangstd** [comment]
你好，这个我询问下相关同事，这个包好像有些重复

**Comment by xiaoliangstd** [comment]
有消息会立马回复您

**Comment by acoudgo** [comment]
请问 有可以替代使用的包了吗

**Comment by xiaoliangstd** [comment]
你好，我问了一下，go1机器人 默认是有ros话题 得到相机点云

**Comment by xiaoliangstd** [comment]
您能提供一个联系方式给我嘛

**Comment by acoudgo** [comment]
15940216249

**Comment by Panting007** [comment]
> 你好，我问了一下，go1机器人 默认是有ros话题 得到相机点云

是在哪里呢？我也遇到同样的问题
