### ISSUE TITLE
关于关节控制话题的问题

### ISSUE THREAD

**Issue by yzyyyyy2048** [unitreerobotics/unitree_guide#27]
您好！IOROS类中sendCmd函数以发布者的形式在12个关节控制话题如/a1_gazebo/RL_thigh_controller/command中发布信息，根据rostopic info查询到订阅者直接就是gazebo，请问是gazebo自动订阅的吗，或者在哪里有所设置吗？且gazebo对于话题中的数据类型unitree_legged_msgs/MotorCmd还需要再进行解算吗？谢谢！

**Comment by dbdxnuliba** [comment]
@xiaoliangstd，您说的这个我有疑问，比如MotorCmd.q =0,MotorCmd.qdes =1, 那么计算出得 gazebo相关方面收到的力矩 gazebo相关方面收到的力矩 = MotorCmd.kp*(MotorCmd.q - MotorCmd.qdes) <0 ,则关节指令力矩朝着与MotorCmd.qdes的反向运动，岂不是离MotorCmd.qdes越来越远么，这里假设kd = 0，t_ff = 0的情况下






> 1. 决定 /a1_gazebo/RL_thigh_controller/command 中话题 命名空间 是在各个机器人的description包的 xacro/gazebo.xacro文件的 4-9行代码
> 
> 2.订阅的应该是unitree_legged_control包里面的joint_controller.cpp文件，然后再转发给gazebo吧，中间肯定是会由额外的解算的，但这方面我也不是很懂。详细可以查看下 gazebo_ros方面的内容。 我估计解算应该只是将算一个最终的力矩给gazebo方面的控制器而已。举个例子即 gazebo相关方面收到的力矩 = MotorCmd.kp*(MotorCmd.q - MotorCmd.qdes) + MotorCmd.kd *(MotorCmd.dq - MotorCmd.dqdes) + MotorCmd.t_ff (t_ff 为程序里的前馈力矩)
