### ISSUE TITLE
关于单刚体模型

### ISSUE THREAD

**Issue by Takagi0215** [unitreerobotics/unitree_guide#33]
6.3所述的单刚体模型，是不考虑腿对于动力学的影响。那么在计算惯性张量时，长方体的长宽高是否是机器人机身的长宽高呢？

**Comment by xiaoliangstd** [comment]
你好，这个如果你从简化的思想上可以将长方体的长宽高作为 控制上的单刚体模型的 长宽高 ，然后这个单刚体的重量可以是躯干的重量 加上 腿部连杆 还有关节电机的重量，，，然而这毕竟只是基于一种简化思想，这个模型是不准确的，，所以你还可以你还可以根据实际的控制效果进行一些调试，参考8,5小节，这个小节说了这种调试的细节。   反正单刚体模型只能说尽量准确啰，模型上的不准确产生的误差 剩下的就靠控制器的参数收敛了，所以还需要多进行控制器上的调试

**Comment by xiaoliangstd** [comment]
还有其他的一些单刚体简化模型方法，可以在网上搜下

**Comment by xiaoliangstd** [comment]
不过这样近似，只能说尽量近似吧，哈哈哈，实际他们也不是均匀密度的刚体

**Comment by Takagi0215** [comment]
好的，谢谢！
