### ISSUE TITLE
有关足端力传感器

### ISSUE THREAD

**Issue by Alleneeous** [unitreerobotics/unitree_guide#34]
在书中介绍了足端力传感器，请问仿真环境下有没有提供该传感器的接口呢？

**Comment by xiaoliangstd** [comment]
这部分没有现成的接口，因为unitree_guide的控制器的接触序列是基于时间的，采用足端传感器的是基于事件的步态。但可以自己改，而且机器人的urdf 里也默认加载了 足端传感器的插件
