### ISSUE TITLE
在src/下没有找到test.cpp

### ISSUE THREAD

**Issue by Alleneeous** [unitreerobotics/unitree_guide#35]
在官方书籍的8.6.3，提到了PyPlot类和示例的test.cpp，但是在src文件夹下没有找到该文件

**Comment by xiaoliangstd** [comment]
您可以暂时先看这个 pull requests, 里面的 test.cpp 文件和 官方的文件是一致的 ，https://github.com/unitreerobotics/unitree_guide/pull/4

**Comment by Alleneeous** [comment]
谢谢，今天下午已经配合书籍学习了相关的代码。另外想请问老师，我已经按书上推荐方法进行了操作：
![87353a292dc7ff0c3d51e1e3d36293a](https://user-images.githubusercontent.com/65111761/233300427-649015ab-eb97-4a13-a25f-9877678f484f.jpg)
在CtrlComponents.h的geneObj中进行addplot
![image](https://user-images.githubusercontent.com/65111761/233300758-da6207d4-2c05-44cb-8193-93c3f66cc3d1.png)
并且已经在有限状态机exit中添加了showPlotAll。现在有些疑惑：如果我要监测机身在{s}中的速度，那么我的addframe应该怎么读取数据呢？
