### ISSUE TITLE
仿真效果与书上描述效果不一致

### ISSUE THREAD

**Issue by Robert5659** [unitreerobotics/unitree_guide#38]
1-roslaunch unitree_guide gazeboSim.launch rname:=go1启动仿真后，go1并没有向书上所说的趴在地上，而是就已经站立在仿真环境中。
2-rosrun unitree_guide junior_ctrl 启动控制器后，按1，go1不能如书上所说进入阻尼模式趴下。但是仿真环境中的go1模型有轻微晃动。

**Comment by Robert5659** [comment]
https://user-images.githubusercontent.com/104151525/234166155-aa76d3d5-13d6-4252-811f-b337970516be.mp4

**Comment by xiaoliangstd** [comment]
你好，这个建议换别的电脑试一下
