### ISSUE TITLE
pyplot的问题(已更新最新上传的代码)

### ISSUE THREAD

**Issue by XiaoJichun** [unitreerobotics/unitree_guide#39]
请问将CMakeList中的DEBUG设置为ON后发生报错。我的python版本是2.7.18 和 3.8.10，我的系统是ubuntu20.04.
![debug](https://user-images.githubusercontent.com/131854379/234513211-0d265dcf-4542-428a-929a-d39cfbafa97a.png)
![2_3](https://user-images.githubusercontent.com/131854379/234515500-84d55d73-3b40-485e-8e43-22583e06422c.png)

在我catkin_make时，出现了以下问题：
![issue](https://user-images.githubusercontent.com/131854379/234513024-79972a60-bfdf-4eb1-8205-75f41a07dabd.png)

**Comment by XiaoJichun** [comment]
为啥子不回答我

**Comment by xiaoliangstd** [comment]
您好，不好意思，没注意到，因为以前也有人问过这个问题，这个问题我近段时间会集中处理下，您也可以加一下这个群，群里有其他大佬解决过这个问题：

![IMG_3867 PNG](https://github.com/unitreerobotics/unitree_guide/assets/37007970/3d2c9f1f-102c-482d-93f3-619ae4b9b435)
