### ISSUE TITLE
关于CmdPanel

### ISSUE THREAD

**Issue by yzyyyyy2048** [unitreerobotics/unitree_guide#41]
您好，请问CmdPanel这个类的作用是什么呢，是跟实物机器人的操控有关吗

**Comment by xiaoliangstd** [comment]
你好，这个类 是一个父类，还有两个类也继承了此类，如KeyBoard WirelessHandle, 当将WirelessHandle的指针赋值给CmdPanel 指针时，就和实物机器人有关了。
