### ISSUE TITLE
控制器接受速度命令

### ISSUE THREAD

**Issue by nanbwrn** [unitreerobotics/unitree_guide#42]
请问，base_local_planner模块发布的速度命令 /cmd_vel 在哪里能找到哪 
![052320c00cf95a34981859426b0ce7a](https://user-images.githubusercontent.com/132453617/236606083-64560033-e439-4b91-9fd8-0cbd7f15f005.jpg)

**Comment by xiaoliangstd** [comment]
你好，这个是根据相应的base_local_planner包来发布的，具体可以看一下 roscd base_local_planner, 具体发布的话题，unitree_guide里仅仅是订阅，这个包发布什么 这边订阅后就执行了

**Comment by nanbwrn** [comment]
您说的是这个吗，我在这没找到发布的具体话题，
![base_local_planner](https://user-images.githubusercontent.com/132453617/236608810-4ec277fc-2ea3-435f-b7b5-3eac3217f318.png)

**Comment by nanbwrn** [comment]
我想这模仿着move_base 里的操作把State_Trotting中的摇杆命令覆盖掉，用/cmd_vel发布的命令来运动，现在找到了订阅操作了，我打算再模仿着，进行发布者实现

**Comment by nanbwrn** [comment]
我把发布的速度加在了main.cpp中，并且在State_Tortting类中，覆盖了getUserCmd,最终运行的时候，发现gazebo中go1不能按照发布的速度指令运动。
![发布](https://user-images.githubusercontent.com/132453617/236618987-e965e530-ac13-46a3-a95a-f95a13baebd6.png)
![while](https://user-images.githubusercontent.com/132453617/236619025-55bd3a5c-3572-453d-8cca-456909ff90e1.png)
![订阅](https://user-images.githubusercontent.com/132453617/236619047-e405eee1-06c7-4f36-85e0-413e446a6e95.png)
![State_Tortting h修改](https://user-images.githubusercontent.com/132453617/236619056-35f337ef-9912-4502-a2b2-85cdec8712ba.png)



https://user-images.githubusercontent.com/132453617/236619185-559b588a-a7d7-4cd4-8e64-5d704009d01e.mp4

**Comment by xiaoliangstd** [comment]
你好，那是因为在 State_Trotting里没有接收这个话题后对应的行为，你可以在 calcCmd() 函数里把你接收到的数据，用来修改 _velBody的值，这里修改相当于修改了“参考轨迹”，控制器感受到参考轨迹后，才可以优化出力 去驱动躯干 尽量地跟上参考轨迹。而 原来State_Trotting是没有代码来修改这个参考轨迹的

**Comment by xiaoliangstd** [comment]
例如 
在calcCmd()函数里 头部位置加上
_velBody(0) = _vx;
_velBody(1) = _vy;

**Comment by nanbwrn** [comment]
您好，我在在calcCmd()函数里 头部位置加上_velBody(0) 和_velBody(1)  之后，控制器好像还是没有感受到参考轨迹

![velbody](https://user-images.githubusercontent.com/132453617/236625376-de99aa76-a3a4-4ee6-b9f1-e274de2217d5.png)

**Comment by xiaoliangstd** [comment]
正常来说不会的，你打印出来看看

**Comment by nanbwrn** [comment]
是在回调函数里写一个打印语句吗

**Comment by nanbwrn** [comment]
谢谢老师，我解决了

**Comment by xiaoliangstd** [comment]
![IMG_2A28055C7EF9-1](https://user-images.githubusercontent.com/37007970/236633690-50bfed16-2067-421c-a45d-6242bee5c4a6.jpeg)

**Comment by xiaoliangstd** [comment]
我新建了个群，有啥问题可以在群里提哈，方便沟通
