### ISSUE TITLE
关于落脚点规划的疑问

### ISSUE THREAD

**Issue by XiaoJichun** [unitreerobotics/unitree_guide#43]
请问：在书的p126页中的落脚点规划,公式(9.7)中：
$x_{f} = x_p(p) + v_x(1-p) T_swing + 1/2 v_x T_stance + k_x (v_x - V_{xd}) $
$x_p(p)$是足端相对于世界坐标系的的坐标，还是机身相对于世界坐标系的坐标。
因为，在程序中是机身相对于世界坐标系的坐标。如下图(_est->getPosition())所示。

![FeetEndCal](https://github.com/unitreerobotics/unitree_guide/assets/131854379/581e50b3-73be-44c8-bb02-9ede1229ddc4)

**Comment by xiaoliangstd** [comment]
已在群里回复
