### ISSUE TITLE
关于gazebo仿真问题

### ISSUE THREAD

**Issue by gh18406468101** [unitreerobotics/unitree_guide#45]
![IMG_20230608_155904.jpg](https://github.com/unitreerobotics/unitree_guide/assets/107991095/3f1ded86-a64c-4b68-8a1e-1c97916ff6b3)

我是在这个unitree guide界面邮件在终端打开  然后catkin make 出现这种报错
这一步具体是怎么操作的呢![IMG_20230608_155956.jpg](https://github.com/unitreerobotics/unitree_guide/assets/107991095/2ddf09ce-e4fc-4182-803d-6722c74336a3)

**Comment by gh18406468101** [comment]
请问有答疑群聊吗

**Comment by xiaoliangstd** [comment]
你好，你这个是没有放在ros工作空间内进行编译，需要新建一个ros工作空间，然后再编译。具体细节也可以问问chatgpt

**Comment by xiaoliangstd** [comment]
> 请问有答疑群聊吗

![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=8781014015936492596 skey=@crypt_d752e05f_9e117545a61a775cf7228697a1128c24 mmweb_appid=wx_webfilehelper](https://github.com/unitreerobotics/unitree_guide/assets/37007970/14703c27-e292-478f-bf32-38c8bb044355)
