### ISSUE TITLE
交流群过期了,可以重新发下么,

### ISSUE THREAD

**Issue by dbdxnuliba** [unitreerobotics/unitree_guide#47]
@xiaoliangstd 老师好,我买了一本四足机器人控制算法建模控制与实践书籍,遇到一些问题,
https://github.com/unitreerobotics/unitree_guide/issues/42
看到这里面有交流群,但是过期了,可以重新发下么,谢谢.

另外在求逆解关节theta3的时候
![image](https://github.com/unitreerobotics/unitree_guide/assets/13350158/b7d725bd-c60d-4768-ab70-ae7419aee547)

这里上图的labad是什么参数呀,在书中没有找到相关的解释.
![image](https://github.com/unitreerobotics/unitree_guide/assets/13350158/37bf68aa-48a0-4b7d-80f6-a1cb3241fbf4)

**Comment by xiaoliangstd** [comment]
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=1025368565319583106 skey=@crypt_d752e05f_caea45cfc7295c4a3daac387a922d484 mmweb_appid=wx_webfilehelper](https://github.com/unitreerobotics/unitree_guide/assets/37007970/deb2d109-4e9a-415b-b321-c4e83cd40424)

**Comment by xiaoliangstd** [comment]
你好，这个问题等今天上班后，我再回复您

**Comment by dbdxnuliba** [comment]
好的，感谢感谢

**Comment by dbdxnuliba** [comment]
看到了书中图5.3有写
