### ISSUE TITLE
Invoking "make -j2 -l2" failed

### ISSUE THREAD

**Issue by benken9** [unitreerobotics/unitree_guide#5]
I have fail to run cmake on catkin_ws2
Here is the output

![output](https://user-images.githubusercontent.com/103132170/224381359-26a970a3-73ff-4b1a-b7e5-04a80877de5d.jpg)

Here is my catkin_ws2 
![image](https://user-images.githubusercontent.com/103132170/224381539-0cc5a07f-5c98-4eea-b644-8f7ab4c87378.png)

Could you please help me to solve it.

**Comment by Rorschach7771** [comment]
you could try "**sudo apt install lib-lcm-dev**" .
