### ISSUE TITLE
请问能再发一下交流群链接吗？

### ISSUE THREAD

**Issue by Qianzhong-Chen** [unitreerobotics/unitree_guide#50]
刚刚开始学习这本书的内容，之前的图片链接都失效了，感谢感谢！

**Comment by xiaoliangstd** [comment]
你好，这个是非正式群，不过有什么问题都可以交流

![IMG_5565 PNG](https://github.com/unitreerobotics/unitree_guide/assets/37007970/0f65549d-f394-4d8e-b75f-cc996da40bf9)
