### ISSUE TITLE
请问如何直接定义go1的位置和姿态来替代keyboard

### ISSUE THREAD

**Issue by wyzhang24** [unitreerobotics/unitree_guide#51]
您好，如果我想直接控制go1在simulation里到达某一个具体的位置以及姿态，如何把keyboard给替换掉呀？请问可以直接把keyboard中的`ChangeValue`函数里的`userValue`给覆盖掉成想要的位置和姿态吗？
另外想问下您的书在美国有办法买到吗？或者有什么线上版本可以参考吗？谢谢！

**Comment by wyzhang24** [comment]
试了一下好像并不行。我hardcode了`userValue.ly = 1.; 我感觉好像这里的value是一个相对位置。当它不等于0的时候，机器人就会一直走。

**Comment by xiaoliangstd** [comment]
你好，你可以直接查看State_Trotting 的 _Pcd变量，直接设置该变量，就可以设置期望位置

**Comment by xiaoliangstd** [comment]
这里有一个非正式交流群，有啥问题可以在群里交流

![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=8781014015936492596 skey=@crypt_d752e05f_9e117545a61a775cf7228697a1128c24 mmweb_appid=wx_webfilehelper](https://github.com/unitreerobotics/unitree_guide/assets/37007970/89f5529a-af44-4397-9362-04c2428b471e)
