### ISSUE TITLE
调试BalanceTest状态，1条腿的足端力数值过大

### ISSUE THREAD

**Issue by Wangxlg** [unitreerobotics/unitree_guide#55]
<img width="521" alt="屏幕截图 2023-07-13 160327" src="https://github.com/unitreerobotics/unitree_guide/assets/101534487/0ec25b75-bbdb-466d-b9ca-034d12453cf2">
第1条腿的足端力数值比其它3条腿的数值大出很多，机器人直接飞了，请问这是什么原因呢？

**Comment by xiaoliangstd** [comment]
你好，这里有个非正式交流群，你可以把问题详细描述一下，这边我帮你分析

![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=3235395373362744659 skey=@crypt_d752e05f_a8fc3e46ff2aa519ebc697f1ae5a53c0 mmweb_appid=wx_webfilehelper](https://github.com/unitreerobotics/unitree_guide/assets/37007970/48d73f44-d070-4883-89ed-1ef9b0478876)
