### ISSUE TITLE
底层控制时电机的力矩赋值

### ISSUE THREAD

**Issue by FuSiyuka** [unitreerobotics/unitree_guide#60]
想用底层控制完成一个趴下的动作，将GO1悬挂后运行代码各关节转动角度符合预期，解除悬挂后运行代码GO1直接倒下，怀疑是没给电机适当力矩造成的。控制电机的力矩赋值通过什么公式或算法得出？是否能通过算法令GO1自主规划力矩?

**Comment by xiaoliangstd** [comment]
你好，四足机器人 趴下动作 应该来说是一个非常简单的动作，您具体可以参考 [State_FixedStand.cpp] (https://github.com/unitreerobotics/unitree_guide/blob/main/unitree_guide/src/FSM/State_FixedStand.cpp) 里的kp kd 设置，我怀疑是你的kp kd 参数给太小导致的。
