### ISSUE TITLE
大佬，编译成功，但是运行不了guide怎么办

### ISSUE THREAD

**Issue by NicholasEinstein** [unitreerobotics/unitree_guide#7]
执行./devel/lib/unitree_guide/junior_ctrl
然后显示[ERROR] Function setProcessScheduler failed.

**Comment by xiaoliangstd** [comment]
你好，这个可以书里有讲到为什么，简单的说 可以在前面加上sudo  ./devel/lib/unitree_guide/junior_ctrl
