### ISSUE TITLE
能再发下交流群群号吗？亲~~

### ISSUE THREAD

**Issue by abloomyt** [unitreerobotics/unitree_guide#73]
可能有些问题想问

**Comment by xiaoliangstd** [comment]
你好，您可以直接在issues里提问，我们也会即时回答的

**Comment by abloomyt** [comment]
谢谢你的回复！那我就不客气了！
State_Trotting.cpp中触地脚的力控制程序关于角度那部分：
_yawCmd = _yawCmd + _dYawCmd * _ctrlComp->dt;
_Rd = rotz(_yawCmd);
_dWbd  = _kpw*rotMatToExp(_Rd*_G2B_RotMat) + _Kdw * (_wCmdGlobal - _lowState->getGyroGlobal());
这里的_Rd的意思是不是目标姿态与0时刻姿态之间的差？但书中的意思是目标姿态与当前（上一时刻）姿态之的差，这里我有点不太明白

**Comment by xiaoliangstd** [comment]
> 谢谢你的回复！那我就不客气了！ State_Trotting.cpp中触地脚的力控制程序关于角度那部分： _yawCmd = _yawCmd + _dYawCmd * _ctrlComp->dt; _Rd = rotz(_yawCmd); _dWbd = _kpw_rotMatToExp(_Rd__G2B_RotMat) + _Kdw * (_wCmdGlobal - _lowState->getGyroGlobal()); 这里的_Rd的意思是不是目标姿态与0时刻姿态之间的差？但书中的意思是目标姿态与当前（上一时刻）姿态之的差，这里我有点不太明白

从仿真里看应该是世界坐标系下的期望姿态。

**Comment by xiaoliangstd** [comment]
你可以尝试按这样的方式改一下_Rd, 然后重新编译运行，就会发现它始终会保持和世界坐标系水平。
![Screenshot from 2024-04-23 12-16-39](https://github.com/unitreerobotics/unitree_guide/assets/37007970/8b57b63f-2cdb-4ae8-802a-6b89baa31535)

**Comment by abloomyt** [comment]
嗯嗯，但是书的意思是期望姿态相对于当前姿态的差，所以我有点误解
![b3d4456b80e17bb7c451bf10d4749130](https://github.com/unitreerobotics/unitree_guide/assets/89628987/4b557b65-a5a2-41a4-b5cd-075931bfb4d7)

**Comment by abloomyt** [comment]
但是这两个姿态差不是同一个差吧，
1.代码中是相对于世界坐标系下的姿态差R1
2.书中是相对于当前姿态的姿态差R2，当前姿态不一定与世界坐标系重合吧

**Comment by xiaoliangstd** [comment]
> 但是这两个姿态差不是同一个差吧， 1.代码中是相对于世界坐标系下的姿态差R1 2.书中是相对于当前姿态的姿态差R2，当前姿态不一定与世界坐标系重合吧

按你的理解，应该是 Rsb * R = Rd ，中的 R , 才是 姿态差嘛

**Comment by abloomyt** [comment]
我明白都是姿态差，但是我觉得书上的姿态差和代码上的姿态差不是同一个姿态差
