### ISSUE TITLE
Need Base Velocity of Unitree Go2 for Policy Observations

### ISSUE THREAD

**Issue by BibsCode** [unitreerobotics/unitree_guide#83]
We are working with a policy that requires the base velocity of the Unitree Go2, which is part of the observations. 
The base velocity is published by the sports mode on ROS, but we need to deactivate the sports service because we want to send low-level commands.

**Problem**:
- We need the base velocity for our policy observations.
- The base velocity is currently published by the sports mode on ROS.
- We need to deactivate the sports service to send low-level commands, which stops the publication of the base velocity.

**Questions**:
- Is there an alternative way to calculate the base velocity using a formula or algorithm?
- Is it possible to configure the system so that the sports topic continues to be published even when the sports service is deactivated?
- How is the base velocity internally calculated or determined by the Unitree Go2? Understanding this might help us replicate the calculation when the sports service is off.

Thank you!

**Comment by xiaoliangstd** [comment]
I think the best way is to delete the base velocity from your observation.

**Comment by xiaoliangstd** [comment]
Or you could refer to this estimator: [Estimator.cpp](https://github.com/unitreerobotics/unitree_guide/blob/main/unitree_guide/src/control/Estimator.cpp). It will output the base velocity. However, the estimator requires the contact state as an input, but when the robot is driven by a reinforcement learning (RL) policy, it often results in an uncertain contact state.

**Comment by xiaoliangstd** [comment]
An irregular contact state

**Comment by BibsCode** [comment]
Can you explain me, how is the base velocity is calculated. The implementation in the "Estimator.cpp" file is not entirely clear to me.
Also I doesn't get what the contact state representing in this case.

Thank for your assistance.

**Comment by xiaoliangstd** [comment]
This explanation is a bit complicated, and you may need to read the book 《Quadruped Robot Control Algorithm-Modeling, Control and Practice》. In summary, the base velocity in observations is not necessary, as in walk-these-ways.

**Comment by BibsCode** [comment]
Thanks for your help, I will train the policy without the BaseVelocity.

**Comment by xiaoliangstd** [comment]
> Thanks for your help, I will train the policy without the BaseVelocity.

You're welcome!
