### ISSUE TITLE
Ubuntu20.04正常运行，但是狗站立起来后会直接摔倒无法按键操控运动，请问是无法在20.04中运行吗

### ISSUE THREAD

**Issue by dstx123** [unitreerobotics/unitree_guide#9]

**Comment by xiaoliangstd** [comment]
你好，我就是在20.04下跑的。这边还是建议你发个视频或者终端截图上来，这边仅凭文字无法判断

**Comment by dstx123** [comment]
> 你好，我就是在20.04下跑的。这边还是建议你发个视频或者终端截图上来，这边仅凭文字无法判断

您好！这是我运行的结果，按了2之后站起来，然后按别的就直接摔倒了，请问这是为什么呀
https://user-images.githubusercontent.com/51892853/224923647-80164b47-61cf-4985-8d45-c907f35944e3.mp4

**Comment by dstx123** [comment]
![image](https://user-images.githubusercontent.com/51892853/224925097-38483ebf-068f-4697-98d1-0f86a087b3ba.png)
![image](https://user-images.githubusercontent.com/51892853/224925153-4e6562e2-2888-4045-be83-70101611f0b4.png)
先按2之后能正常站起来，但是按了4之后就摔倒了

**Comment by xiaoliangstd** [comment]
或者您还是录个视频吧，我这边看你的终端显示的信息，都是正常的

**Comment by dstx123** [comment]
> > 你好，我就是在20.04下跑的。这边还是建议你发个视频或者终端截图上来，这边仅凭文字无法判断
> 
> 您好！这是我运行的结果，按了2之后站起来，然后按别的就直接摔倒了，请问这是为什么呀 https://user-images.githubusercontent.com/51892853/224923647-80164b47-61cf-4985-8d45-c907f35944e3.mp4

这个链接里面就是视频诶

**Comment by xiaoliangstd** [comment]
我看终端还 提示 超时， 可以在前面加上 sudo ./devel/lib/unitree_guide/junior_ctrl , 这样可以把进程优先级提高，您的现在算一次花了5.2毫秒，就是约192hz，我们正常可以跑500hz

**Comment by xiaoliangstd** [comment]
我看到了，您应该是用WSL来跑，我们没有在WSL上测试过，建议还是用虚拟机或者双系统跑吧。我猜测应该是步态程序里用的系统时间函数在WSL上用不了，有可能。

**Comment by dstx123** [comment]
> 

不是用的wsl，这是用的向日葵连接的远程服务器。sudo ./devel/lib/unitree_guide/junior_ctrl 这个命令无法执行提示no such file or directory。去掉sudo可以正常运行

**Comment by dstx123** [comment]
超时是在摔倒之后过了一会儿才发生的，我录个屏发给您看看吧

**Comment by dstx123** [comment]
稍等一下，我压缩一下文件

**Comment by xiaoliangstd** [comment]
想问下，您有试过在其他电脑跑嘛，会不会有这个问题

**Comment by dstx123** [comment]
https://user-images.githubusercontent.com/51892853/224938137-89ce8f42-09e6-416c-bc84-f4de0c1c404a.mp4

视频j结果是这样的您看看，手头没有别的电脑诶

**Comment by xiaoliangstd** [comment]
你好，我刚看了下你的视频，有一点疑惑，unitree_guide 的FSM里是有保护的即FSM.cpp 里面的checkSafty()函数，一般在机器人摔倒后，这个函数会返回true，从而让机器人从trotting 状态 转到 passive 状态即阻尼状态，此时机器人腿部会停下来。但从您的效果来看，这个函数明显没起作用，看下能否先debug这个问题。

**Comment by xiaoliangstd** [comment]
至于它为什么会这样，我这边有朋友遇到过这个奇怪现象，我先和他咨询下，然后再答复你

**Comment by dstx123** [comment]
麻烦您了！

**Comment by dstx123** [comment]
会不会判断摔倒的传感器没有正常启动？我看xacro文件在melodic和neotic两个版本之间是有区别的。

**Comment by xiaoliangstd** [comment]
> 会不会判断摔倒的传感器没有正常启动？我看xacro文件在melodic和neotic两个版本之间是有区别的。

应该不会，这个函数的判断是直接从IMU的姿态解算得到的旋转矩阵判断的。您那边方便在它翻转过来的时候把身体的旋转矩阵打印出来看下？

**Comment by dstx123** [comment]
我该怎么打印呀，改哪个文件

**Comment by xiaoliangstd** [comment]
bool FSM::checkSafty(){
    // The angle with z axis less than 60 degree
    std::cout<<"getRotMat: "<<std::endl;
    std::cout<<_ctrlComp->lowState->getRotMat()<<std::endl;
    std::cout<<std::endl;
    if(_ctrlComp->lowState->getRotMat()(2,2) < 0.5 ){
        return false;
    }else{
        return true;
    }
}

**Comment by xiaoliangstd** [comment]
https://user-images.githubusercontent.com/37007970/224957535-bb0361bc-1256-4470-bc13-66b541214bc1.mp4

**Comment by dstx123** [comment]
我这里这个数据没有变过诶

https://user-images.githubusercontent.com/51892853/224962021-4cf49903-8127-4e05-b256-d0f34103b429.mp4

**Comment by dstx123** [comment]
一直都是单位矩阵

**Comment by xiaoliangstd** [comment]
这个应该得一步步排查了，看下这里的函数会有变化嘛，里面的值
void IOROS::imuCallback(const sensor_msgs::Imu & msg)
{ 
    _lowState.imu.quaternion[0] = msg.orientation.w;
    _lowState.imu.quaternion[1] = msg.orientation.x;
    _lowState.imu.quaternion[2] = msg.orientation.y;
    _lowState.imu.quaternion[3] = msg.orientation.z;

    _lowState.imu.gyroscope[0] = msg.angular_velocity.x;
    _lowState.imu.gyroscope[1] = msg.angular_velocity.y;
    _lowState.imu.gyroscope[2] = msg.angular_velocity.z;
    
    _lowState.imu.accelerometer[0] = msg.linear_acceleration.x;
    _lowState.imu.accelerometer[1] = msg.linear_acceleration.y;
    _lowState.imu.accelerometer[2] = msg.linear_acceleration.z;
}

**Comment by dstx123** [comment]
我尝试直接在函数里面std::cout没法输出，然后我看这个数据好像是作为/trunk_imu话题订阅的，我直接查看这个话题提示这样
![image](https://user-images.githubusercontent.com/51892853/224971278-b60341e0-9410-4bb1-bbf3-c610167db3d8.png)

**Comment by dstx123** [comment]
我尝试按照网上说的rosparam set use_sim_time false执行后rostopic echo /trunk_imu会卡住，狗仍然会摔倒

**Comment by xiaoliangstd** [comment]
好的，您的这个情况暂时我没有遇到，我这边先分析下解决方案

**Comment by dstx123** [comment]
麻烦您了！

**Comment by LJoson** [comment]
> 我看到了，您应该是用WSL来跑，我们没有在WSL上测试过，建议还是用虚拟机或者双系统跑吧。我猜测应该是步态程序里用的系统时间函数在WSL上用不了，有可能。

hello @xiaoliangstd , i use this repo in wsl2 but it don not have the wrong according to what u said

**Comment by dstx123** [comment]
解决了，是ros环境的问题，导致没法正常加载imu。我卸载ros之后重新用鱼香ros一键安装就可以了。谢谢！

**Comment by fan-ziqi** [comment]
# 已解决，附解决方法
#6 #1 
查看gazebo的imu数据，一切正常
![image](https://user-images.githubusercontent.com/62320343/225698019-ca81420f-3353-4184-8f70-51ea840fbc54.png)
但下图中话题未发布
<img width="550" alt="92b0294661015e98d20479b70b66c57" src="https://user-images.githubusercontent.com/62320343/225697815-ec6bbbdf-858c-4cc7-95f6-549c1c2edcf3.png">
遂怀疑gazebo与ros通信的插件有问题
在launch文件中的gazebo部分添加`<arg name="verbose" default="true"/>`，查看终端提示找不到插件
![1](https://user-images.githubusercontent.com/62320343/225697434-1f02d297-a25b-4337-9fc7-699e3f5d999a.jpg)
经过定位，缺少`ros-noetic-gazebo-plugins`、`ros-noetic-gazebo-ros-pkgs`这两个包
安装对应版本的包即可
```
sudo apt install ros-noetic-gazebo-ros-pkgs  ros-noetic-gazebo-msgs  ros-noetic-gazebo-plugins  ros-noetic-gazebo-ros-control
```

**Comment by xiaoliangstd** [comment]
> # 已解决，附解决方法
> 
> #6 #1 查看gazebo的imu数据，一切正常 ![image](https://user-images.githubusercontent.com/62320343/225698019-ca81420f-3353-4184-8f70-51ea840fbc54.png) 但下图中话题未发布 <img alt="92b0294661015e98d20479b70b66c57" width="550" src="https://user-images.githubusercontent.com/62320343/225697815-ec6bbbdf-858c-4cc7-95f6-549c1c2edcf3.png"> 遂怀疑gazebo与ros通信的插件有问题 在launch文件中的gazebo部分添加`<arg name="verbose" default="true"/>`，查看终端提示找不到插件 ![1](https://user-images.githubusercontent.com/62320343/225697434-1f02d297-a25b-4337-9fc7-699e3f5d999a.jpg) 经过定位，缺少`ros-noetic-gazebo-plugins`、`ros-noetic-gazebo-ros-pkgs`这两个包 安装对应版本的包即可
> 
> ```
> sudo apt install ros-noetic-gazebo-ros-pkgs  ros-noetic-gazebo-msgs  ros-noetic-gazebo-plugins  ros-noetic-gazebo-ros-control
> ```

强的大哥！

**Comment by dstx123** [comment]
谢谢！

> # 已解决，附解决方法
> #6 #1 查看gazebo的imu数据，一切正常 ![image](https://user-images.githubusercontent.com/62320343/225698019-ca81420f-3353-4184-8f70-51ea840fbc54.png) 但下图中话题未发布 <img alt="92b0294661015e98d20479b70b66c57" width="550" src="https://user-images.githubusercontent.com/62320343/225697815-ec6bbbdf-858c-4cc7-95f6-549c1c2edcf3.png"> 遂怀疑gazebo与ros通信的插件有问题 在launch文件中的gazebo部分添加`<arg name="verbose" default="true"/>`，查看终端提示找不到插件 ![1](https://user-images.githubusercontent.com/62320343/225697434-1f02d297-a25b-4337-9fc7-699e3f5d999a.jpg) 经过定位，缺少`ros-noetic-gazebo-plugins`、`ros-noetic-gazebo-ros-pkgs`这两个包 安装对应版本的包即可
> 
> ```
> sudo apt install ros-noetic-gazebo-ros-pkgs  ros-noetic-gazebo-msgs  ros-noetic-gazebo-plugins  ros-noetic-gazebo-ros-control
> ```
